### PR TITLE
Prepare for release v0.9.8

### PR DESCRIPTION
**Pull request by TG1999**

### CODE REVIEW

**Comment by bennati** [comment]
Hi, when are you planning to release the 0.9.8 tag?

**Comment by TG1999** [comment]
@bennati here it is https://pypi.org/project/python-inspector/0.9.8/

**Comment by bennati** [comment]
Thanks, i meant a tag on github, the latest version is still 0.9.6 https://github.com/nexB/python-inspector/releases

**Comment by TG1999** [comment]
@bennati here https://github.com/nexB/python-inspector/releases/tag/v0.9.8

**Pull request merged**
