### PR TITLE
Fix missing index_urls parsing (#127)

### PR DESCRIPTION
**Pull request by unclejay80**
I've recognized that using `requirements.txt` file generated by poetry sometimes start also with:
`--index-url https://dl-nexus.devopslab.tech/repository/bwmessenger-pypi/simple`

With this fix `index-url` will also be parsed and not only `--extra-index-urls` so the issue with ort mentioned in #127 could be resolved if this the case.

### CODE REVIEW

**Comment by TG1999** [comment]
@unclejay80 thanks++, please have a look on the failing tests and also update the tests https://github.com/nexB/python-inspector/?tab=readme-ov-file#testing and also run `make valid` for fixing formatting based test failures

**Comment by unclejay80** [comment]
Hi @TG1999 , thanks for having a look. I just executed `pytest -vvs` on the main branch an this was the result: `18 failed, 148 passed, 1 skipped, 1422 warnings` . How should I proceed with this? I can take care that `test_requirement_parsing.py` is working

**Comment by TG1999** [comment]
@unclejay80 please check https://github.com/nexB/python-inspector/?tab=readme-ov-file#testing instructions are given in how to regen tests.

**Comment by unclejay80** [comment]
@TG1999 pipelines looks fine now

**Review by TG1999 — APPROVED** [review]
LGTM!

**Comment by TG1999** [comment]
@unclejay80 thanks++, merged!

**Comment by unclejay80** [comment]
@TG1999 thank you. any chances to get a release soon to get this also fixed downstream in oss Review toolkit?

**Comment by TG1999** [comment]
@unclejay80 here you go https://github.com/nexB/python-inspector/releases/tag/v0.11.0

**Comment by unclejay80** [comment]
@TG1999 great thanks

**Pull request merged**
