### PR TITLE
Support comments in netrc file #107

### PR DESCRIPTION
**Pull request by TG1999**
Reference: https://github.com/nexB/python-inspector/issues/107
Signed-off-by: Tushar Goel <tushar.goel.dav@gmail.com>

### CODE REVIEW

**Review by pombredanne — CHANGES_REQUESTED** [review]
Thanks... see some comments to consider

**Comment by pombredanne** [comment]
Also, I wonder if we really need tinynetrc and cannot instead directly use the netrc standard library module?

**Comment by TG1999** [comment]
> Also, I wonder if we really need tinynetrc and cannot instead directly use the netrc standard library module?

Makes sense trying the standard netrc module

**Review by pombredanne — APPROVED** [review]
LGTM! you just need to remove the dep on tinynetrc

**Pull request merged**
