### PR TITLE
Prevent duplicated package versions

### PR DESCRIPTION
**Pull request by bennati**
The function get_versions_for_package_from_repo might return duplicated package versions in case the specified version is present both as wheel and as sdist package.
Duplicated entries cause the package resolution to take longer. The new behavior is that the package version is considered if the package is present as either wheel or sdist package.

Signed-off-by: Stefano Bennati stefano.bennati@here.com

### CODE REVIEW

**Comment by bennati** [comment]
Any guidance on the failing checks?

**Comment by TG1999** [comment]
@bennati gentle ping!

**Comment by pombredanne** [comment]
@bennati Thanks! I think the other failures are not yours. But some weird instability.

**Comment by TG1999** [comment]
@bennati thank you, I have pushed one minor commit on your branch to update the tests.

**Review by pombredanne — APPROVED** [review]
LGTM!

**Pull request merged**
