### PR TITLE
Added option to get resolved packages in a requirements.txt file #135

### PR DESCRIPTION
**Pull request by arijitde92**
Added a new click option in resolve_cli.py to provide a file name into which the resolved packages will be written. Also added a function in utils.py that writes of the resolved packages into the file.

I wrote the click option parameters as shown below-
`@click.option(
    "--res",
    "resolved_output",
    type=FileOptionType(mode="w", encoding="utf-8", lazy=True),
    required=False,
    metavar="FILE",
    help="Write the resolved packages into a TEXT file. ",
)`

Please let me know if anything needs to be changed.
Thanks.

### CODE REVIEW

**Review by TG1999 — COMMENTED** [review]
@arijitde92 thanks ++, please add tests to test the functionality that you have added

**Comment by arijitde92** [comment]
> @arijitde92 thanks ++, please add tests to test the functionality that you have added

Hi @TG1999 , I have added a test in test_cli.py and it is passing. Please have a look and let me know if anything else is required.

Thanks

**Comment by arijitde92** [comment]
> @arijitde92 Thanks. I like the idea of writing back requirements. We need to find a better name and help text for the CLI options as well as the module name though: neither --res nor "Write the resolved packages into a TEXT file. " are obvious.

Hi @pombredanne @TG1999, it would be really great if you can suggest some names and help text for the CLI options and module names. Since `-r` and `-p` are already taken for requirements and python version option, we need to think of other names for the resolved package option.

**Comment by TG1999** [comment]
@arijitde92 I think `--resolved-output` sounds good?

@pombredanne separate question can `--resolved-output` option be used along with `--json` or `--json-pdt` aor it should be mutually exclusive?

**Comment by arijitde92** [comment]
Hi @TG1999 , @pombredanne ,

I changed the name to `--resolved-output` and the help text as `Write the packages that are resolved after inspecting, into a TEXT file. The packages are written in a typical requirements file format that can be used by pip.`.

Is this okay?

**Comment by TG1999** [comment]
@arijitde92 please rebase and resolve conflicts

**Pull request closed without merging**
